name: github pages
on:
  pull_request:
    branches:
      - main
      - nextjs
  push:
    branches:
      - main
      - nextjs
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          node-version: '19.x'
      - name: install
        run: yarn install --frozen-lockfile
      - name: build
        run: ./build.sh
        env:
          TYPE: ${{ secrets.TYPE }}
      - name: add nojekyll
        run: touch ./out/.nojekyll
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
