concurrency:
  cancel-in-progress: false
  group: pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: yarn
          node-version: latest
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Upload
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./build/client
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        name: Deploy
        uses: actions/deploy-pages@v4
name: GitHub Pages
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
  pages: write
